image:
  file: .gitpod.Dockerfile

workspaceLocation: 'project'
checkoutLocation: 'project'

tasks:
  - before: |
      sudo touch /workspace/.bash_history
      sudo cp /workspace/project/.freeCodeCamp/.bashrc ~/.bashrc
      sudo cp /workspace/project/.freeCodeCamp/.psqlrc ~/.psqlrc
      sudo cp /workspace/project/.freeCodeCamp/postgresql.conf /etc/postgresql/12/main/postgresql.conf
      sudo cp /workspace/project/.freeCodeCamp/pg_hba.conf /etc/postgresql/12/main/pg_hba.conf
      sudo touch /workspace/pg.log
      sudo touch /workspace/queryResults.log
      sudo chmod -R 777 /workspace
      sudo chown -R postgres:postgres /var/lib/postgresql/12/main

    command: |
      pg_stop && sudo service postgresql start && echo "SELECT 'CREATE USER freecodecamp WITH CREATEDB' WHERE NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname='freecodecamp')\gexec" | psql -U postgres -X
      exit

vscode:
  extensions:
    - CodeRoad.coderoad
